spring:
  application:
    name: employeemanagement
  datasource:
    url: jdbc:postgresql://localhost:5432/employeemanagementdb
    username: dedalusAdmin
    password: adminPass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_slq: true
